### PR TITLE
Fix building of apiextractor target.

### PR DESCRIPTION
**Pull request by f3nix**
Hi!
After recent changes I get:

```In file included from /home/f3nix/devel/freecad/my_freecad_qt5/shiboken2/ApiExtractor/docparser.cpp:29:0:
/usr/include/libxslt/xsltutils.h:19:26: fatal error: libxml/xpath.h: Nie ma takiego pliku ani katalogu
compilation terminated.
ApiExtractor/CMakeFiles/apiextractor.dir/build.make:811: polecenia dla obiektu 'ApiExtractor/CMakeFiles/apiextractor.dir/docparser.cpp.o' nie powiodły się
make[2]: *** [ApiExtractor/CMakeFiles/apiextractor.dir/docparser.cpp.o] Błąd 1
CMakeFiles/Makefile2:152: polecenia dla obiektu 'ApiExtractor/CMakeFiles/apiextractor.dir/all' nie powiodły się
make[1]: *** [ApiExtractor/CMakeFiles/apiextractor.dir/all] Błąd 2
Makefile:138: polecenia dla obiektu 'all' nie powiodły się
make: *** [all] Błąd 2```

This PR fixes this issue.

Cheers,
Mateusz

### CODE REVIEW

**Comment by f3nix** [comment]
Ping @thopiekar! :)

I think this should be interesting for you. It fixes your PPA build issues.

Cheers,
Mateusz

**Comment by thopiekar** [comment]
I noticed this PR and I left it unmerged as @ctismer just made this change (removed the capital S from the variables) to get the tests working. I don't know why the change made a difference, but as he recently changed this part and it reverts his work, I think he should decide on this PR :/

**Comment by f3nix** [comment]
Thanks @thopiekar!
Could You please comfirm the build error with a clean build directory?

The problem is that:
```
find_package(LibXml2 2.6.32)
```
sets:
```
LIBXML2_INCLUDE_DIR - The LibXml2 include directory
```
cmake doc: [FindLibXml2](https://cmake.org/cmake/help/v3.0/module/FindLibXml2.html)

and
```
find_package(LibXslt 1.1.19)
```
sets:
```
LIBXSLT_INCLUDE_DIR - the LibXslt include directory
```
cmake doc: [FindLibXslt](https://cmake.org/cmake/help/v3.0/module/FindLibXslt.html)

LIBXML_INCLUDE_DIRS and LIBXSLT_INCLUDE_DIR are _empty_ so it causes build failure.
It is clearly a typo.

@ctismer - am I missing something? Thanks.

Cheers,
Mateusz

**Comment by thopiekar** [comment]
In this case I would check whether LIBXML2_INCLUDE_DIR is NULL and if
LIBXML2_INCLUDE_DIRS is not NULL set LIBXML2_INCLUDE_DIR via
LIBXML2_INCLUDE_DIRS.
Same for Xslt.
And add a comment that this is a workaround on top of that.

**Comment by thopiekar** [comment]
Do you mean the error we had before? I think Travis is collecting old build logs, isn't it?

**Comment by f3nix** [comment]
For example LIBXML2_INCLUDE_DIRS appears only ones (note the 'S'):

```
f3nix@bigspider:~/pyside2/shiboken2$ grep -R 'LIBXML2_INCLUDE_DIRS' .                                                                                                                                                                      
./ApiExtractor/CMakeLists.txt:    set(APIEXTRACTOR_EXTRA_INCLUDES ${LIBXSLT_INCLUDE_DIRS} ${LIBXML2_INCLUDE_DIRS})
```

And it is not set anywhere... So checking for its value is not necessary (nor is setting it's value with LIBXML2_INCLUDE_DIR).

These are the results of compiliing with this PR's changes:
```
f3nix@bigspider:~/devel/freecad/my_freecad_qt5/shiboken2/build-release$ make test

--- CUT ---
--- CUT ---
100% tests passed, 0 tests failed out of 169

Total Test time (real) =  10.19 sec
```

Cheers,
Mateusz

P.S. I mean the error from the first comment or this [Your shiboken2 PPA](https://launchpadlibrarian.net/242236780/buildlog_ubuntu-wily-amd64.shiboken2_2.0.0.dev0-0~201602231546~rev1605~pkg23~ubuntu15.10.1_BUILDING.txt.gz)

**Comment by f3nix** [comment]
And here is a Travis build using this PR. It passes.

https://travis-ci.org/f3nix/pyside2-setup/builds/116212527

**Comment by thopiekar** [comment]
Looks good. I'm sure @ctismer will like it :smiley:

**Comment by thopiekar** [comment]
Ah, I forget about this issue! It is still causing my builds to fail: #38
Sadly no feedback for @ctismer so far :disappointed:

**Comment by thopiekar** [comment]
Got an idea! Could you do something like that:

IF (DEFINED DIRS)
SET(API_INCLUDES DIRS)
ELSE()
SET(API_INCLUDES DIR)
ENDIF()

So in short: if there is a variable called DIRS use DIRS and if not DIR should be at least there and use DIR instead.

I would really like to know whether it is a CMake issue or whatever.

**Comment by f3nix** [comment]
***CSI mode on*** ;)

I think @ctismer tried to fix Travis builds.

Look at the Travis log: https://travis-ci.org/PySide/pyside2-setup/builds

Commits:
22.02.2016
9d0411fb5898b9ff70302572d1f0fbec85beb1ca - failed
8d69c61b26a0a5440c090e47ba815ab87fb0bb9c - failed
b534be09abf6e38f2a27aeddcbbb8e00d6c9e4e7 - failed


23.02.2016
d4c17c826af69547e57882d03d0facd265834fc8 - failed
d486400308b08b299c4f9ad3e32db3a102f0f402 - **passed**

Looking at https://github.com/PySide/pyside2-setup/commit/d486400308b08b299c4f9ad3e32db3a102f0f402

It changes the shiboken2 subproject commit to this: 32d5805b8489db75d20462e76328b7791735073a

Job no 19 failed with linking error:
For example:
```
 undefined reference to `QXmlParseException::message() const'
```
Adding only the second change in CMakeLists.txt would be enough (https://github.com/PySide/shiboken2/commit/32d5805b8489db75d20462e76328b7791735073a#diff-76443dd09c17210eb98573b63052654dR13)

It fixed building on Travis but caused trouble to build at least on Linux.

```
f3nix@bigspider:~/devel/my_pyside2$ ls -l
drwxr-xr-x 11 f3nix f3nix 4096 lut 13 07:09 pyside2
drwxr-xr-x  7 f3nix f3nix 4096 mar 15 20:44 pyside2-setup
drwxr-xr-x 14 f3nix f3nix 4096 lut 13 07:12 shiboken2
f3nix@bigspider:~/devel/my_pyside2$ grep -r "LIBXML2_INCLUDE_DIRS"
f3nix@bigspider:~/devel/my_pyside2$ 
```
No results.

```
f3nix@bigspider:/usr/share/cmake-3.5/Modules$ grep -r "LIBXML2_INCLUDE_DIRS"
f3nix@bigspider:/usr/share/cmake-3.5/Modules$ 
```
No results as well.

The DIRS variable is not set anywhere. It is clearly a typo. Look at the third changed line here: https://github.com/PySide/shiboken2/commit/32d5805b8489db75d20462e76328b7791735073a#diff-76443dd09c17210eb98573b63052654dR13

This is how it might have been introduced.

***CSI mode off***

So changing it back to *_DIR gives us this:
1. Travis builds just fine: https://travis-ci.org/f3nix/pyside2-setup/builds/116212527
2. Linux builds without errors.

Cheers,
Mateusz

**Comment by thopiekar** [comment]
@f3nix Ok, I just believe you now ^^

If it breaks something, blame it on me.

**Comment by f3nix** [comment]
Thank you! :)

**Pull request merged**
