### PR TITLE
Fix incorrect primitive type and add a check

### PR DESCRIPTION
**Pull request by o11c**
This fixes PySide/pyside2#3

### CODE REVIEW

**Comment by o11c** [comment]
Hm, the abort is being triggered for `size_t`, which shouldn't happen since that's a typedef and that should be stripped ...

**Comment by o11c** [comment]
I have no idea what `primitive-type` is supposed to be. A bunch of things that are obviously not primitives are being specified as such in the XML file, and many of them are missing entries in the `QHash` like the one I added.

**Comment by ctismer** [comment]
Thanks for your patch! But the story is not over...
I tried the patch on OS X 10.10, and shiboken crashes now
```
/bin/sh: line 1:  2850 Abort trap: 6           /Users/tismer/src/pyside2-setup/pyside_build/py3.4-qt5.5.0-64bit-debug/shiboken/generator/shiboken --project-file=/Users/tismer/src/pyside2-setup/pyside_build/py3.4-qt5.5.0-64bit-debug/shiboken/shibokenmodule/shibokenmodule.txt
make[2]: *** [shibokenmodule/shiboken/shiboken_module_wrapper.cpp] Error 134
make[1]: *** [shibokenmodule/CMakeFiles/shibokenmodule.dir/all] Error 2
make: *** [all] Error 2
error: Error compiling shiboken
```

**Comment by ctismer** [comment]
This patch can unfortunately not used as it is.
An abort is wrong here, because the code is called often with primitive types which are not declared here.
I'll add the code for debugging.
Also do not replace working type entries with your's, but add them.
The problem might depend from some include file differences. So I eventually
also added 'size_t' and your new type.

Should compile now.

**Pull request merged**
