### PR TITLE
Do not add MULTIARCH suffix if not available.

### PR DESCRIPTION
**Pull request by gbaty**
On some python builds, "sysconfig.get_config_var('MULTIARCH')" returns an empty string.
This case produce python extensions that are not recognized by python interpreter.
This commit fix this issue.

### CODE REVIEW

**Comment by thopiekar** [comment]
Great! What do you think about Python >= 2.0 ? I double checked and also found the same there:
```apt-file find python2.7 | grep dist-packages | grep x86_64-linux-gnu```

**Comment by gbaty** [comment]
Indeed, I think checking PYTHON_MULTIARCH_SUFFIX only is sufficient.
PYTHON_MULTIARCH_SUFFIX come from "sysconfig.get_config_var('MULTIARCH')" and this command returns "" if not supported. So I think we can just check python version for debug suffix

**Comment by thopiekar** [comment]
Correct!

**Comment by gbaty** [comment]
**PR is ready** 

I tried to be as constant as possible:
  - for py2:
    - define release suffix (-dbg or nothing)
    - define full suffix like "-python2.7-dbg"
  - same for py3
  - then if multiarch support, add multiarch suffix

**Comment by thopiekar** [comment]
Ah, sorry, I just wanted to take a closer look.
Should work well :dancer:

**Comment by gbaty** [comment]
No problem. Thanks. Bold was here just to see text among explanation details, not to insist ;)

**Comment by thopiekar** [comment]
I would really like to know whether our changes also work on Windows and OSX or not. MULTIARCH will be of course ignored, but the rest might work.

**Comment by thopiekar** [comment]
Haha, don't worry ^^

**Pull request merged**
